# Generated by Django 6.0.6 on 2026-06-07 01:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceFirmware",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=20, unique=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("esp8266", "ESP8266"),
                            ("esp32", "ESP32"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="firmware/")),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("checksum", models.CharField(max_length=64, unique=True)),
                ("changelog", models.TextField()),
                ("release_notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("testing", "Testing"),
                            ("stable", "Stable"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("deprecated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Device Firmware",
                "verbose_name_plural": "Device Firmware",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("device_name", models.CharField(max_length=255)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("esp8266", "ESP8266"),
                            ("esp32", "ESP32"),
                            ("other", "Other"),
                        ],
                        default="esp8266",
                        max_length=20,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("firmware_version", models.CharField(default="1.0.0", max_length=20)),
                ("mac_address", models.CharField(blank=True, max_length=17, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("inactive", "Inactive"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "temperature",
                    models.FloatField(
                        blank=True,
                        help_text="Last recorded temperature (°C)",
                        null=True,
                    ),
                ),
                (
                    "humidity",
                    models.FloatField(
                        blank=True, help_text="Last recorded humidity (%)", null=True
                    ),
                ),
                (
                    "wifi_signal",
                    models.IntegerField(
                        blank=True, help_text="WiFi signal strength (dBm)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="Appliance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "appliance_type",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("fan", "Fan"),
                            ("switch", "Switch"),
                            ("door", "Door/Gate"),
                            ("pump", "Pump"),
                            ("other", "Other"),
                        ],
                        default="switch",
                        max_length=20,
                    ),
                ),
                (
                    "pin",
                    models.CharField(
                        help_text="V0, V1, V2, etc. or GPIO pin number", max_length=10
                    ),
                ),
                (
                    "virtual_pin",
                    models.CharField(
                        db_index=True,
                        help_text="Virtual pin like V0, V1",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "state",
                    models.IntegerField(choices=[(0, "OFF"), (1, "ON")], default=0),
                ),
                ("icon", models.CharField(default="fa-power-off", max_length=50)),
                ("room", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "power_consumption",
                    models.FloatField(
                        blank=True, help_text="Power consumption in watts", null=True
                    ),
                ),
                ("can_control", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("last_state_change", models.DateTimeField(blank=True, null=True)),
                (
                    "total_on_time",
                    models.BigIntegerField(
                        default=0, help_text="Total ON time in seconds"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appliances",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appliance",
                "verbose_name_plural": "Appliances",
                "ordering": ["room", "name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("pressure", models.FloatField(blank=True, null=True)),
                ("wifi_signal", models.IntegerField(blank=True, null=True)),
                (
                    "wifi_quality",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "uptime",
                    models.BigIntegerField(
                        blank=True, help_text="Uptime in seconds", null=True
                    ),
                ),
                (
                    "free_memory",
                    models.BigIntegerField(
                        blank=True, help_text="Free memory in bytes", null=True
                    ),
                ),
                ("power_consumption", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_logs",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Data",
                "verbose_name_plural": "Device Data",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ApplianceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "previous_state",
                    models.IntegerField(choices=[(0, "OFF"), (1, "ON")]),
                ),
                ("new_state", models.IntegerField(choices=[(0, "OFF"), (1, "ON")])),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("turned_on", "Turned ON"),
                            ("turned_off", "Turned OFF"),
                            ("toggled", "Toggled"),
                            ("auto_on", "Auto ON"),
                            ("auto_off", "Auto OFF"),
                            ("timer_on", "Timer ON"),
                            ("timer_off", "Timer OFF"),
                        ],
                        default="turned_on",
                        max_length=20,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("automation", "Automation"),
                            ("timer", "Timer"),
                            ("device", "Device"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "appliance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="devices.appliance",
                    ),
                ),
                (
                    "triggered_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Appliance History",
                "verbose_name_plural": "Appliance History",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["appliance", "-timestamp"],
                        name="devices_app_applian_8c8a5a_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["user", "-last_seen"], name="devices_dev_user_id_1eb67f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["status"], name="devices_dev_status_bbf58f_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["api_key"], name="devices_dev_api_key_c3d067_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appliance",
            index=models.Index(
                fields=["device", "virtual_pin"], name="devices_app_device__5841b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appliance",
            index=models.Index(fields=["state"], name="devices_app_state_ecbefc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="appliance",
            unique_together={("device", "virtual_pin")},
        ),
        migrations.AddIndex(
            model_name="devicedata",
            index=models.Index(
                fields=["device", "-timestamp"], name="devices_dev_device__246e80_idx"
            ),
        ),
    ]
