# Generated by Django 6.0.6 on 2026-06-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliance",
            name="virtual_pin",
            field=models.CharField(
                db_index=True, help_text="Virtual pin like V0, V1", max_length=10
            ),
        ),
    ]
