# Generated by Django 6.0.6 on 2026-06-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_alter_appliance_virtual_pin"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="device",
            name="devices_dev_api_key_c3d067_idx",
        ),
        migrations.RemoveField(
            model_name="device",
            name="api_key",
        ),
    ]
