# Generated by Django 6.0.6 on 2026-06-07 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_remove_device_devices_dev_api_key_c3d067_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliance",
            name="value",
            field=models.IntegerField(
                blank=True,
                help_text="Numeric slider/display value, e.g. 1-7 for slider or display output",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="appliance",
            name="appliance_type",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("fan", "Fan"),
                    ("switch", "Switch"),
                    ("door", "Door/Gate"),
                    ("pump", "Pump"),
                    ("slider", "Slider"),
                    ("display", "Display"),
                    ("other", "Other"),
                ],
                default="switch",
                max_length=20,
            ),
        ),
    ]
