# Generated by Django 6.0.6 on 2026-06-09 14:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0006_remove_env_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTAUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bin_file",
                    models.FileField(
                        help_text="Binary firmware file (.bin)",
                        upload_to="ota_updates/",
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA256 checksum of file", max_length=64
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Firmware version e.g. v1.2.3", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("downloading", "Downloading"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "download_progress",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "OTA Update",
                "verbose_name_plural": "OTA Updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="watermonitoringdata",
            new_name="devices_wat_device__89887b_idx",
            old_name="devices_wmd_device__0f4d25_idx",
        ),
        migrations.AddField(
            model_name="otaupdate",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ota_updates",
                to="devices.device",
            ),
        ),
    ]
