# Generated by Django 6.0.6 on 2026-06-07 01:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("device_offline_in_app", models.BooleanField(default=True)),
                ("device_online_in_app", models.BooleanField(default=True)),
                ("firmware_update_in_app", models.BooleanField(default=True)),
                ("appliance_control_in_app", models.BooleanField(default=True)),
                ("device_offline_email", models.BooleanField(default=True)),
                ("device_online_email", models.BooleanField(default=False)),
                ("firmware_update_email", models.BooleanField(default=True)),
                ("appliance_control_email", models.BooleanField(default=False)),
                (
                    "email_frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("hourly", "Hourly Digest"),
                            ("daily", "Daily Digest"),
                            ("never", "Never"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("device_offline", "Device Offline"),
                            ("device_online", "Device Online"),
                            ("firmware_update", "Firmware Update"),
                            ("appliance_control", "Appliance Control"),
                            ("system_alert", "System Alert"),
                            ("info", "Information"),
                        ],
                        default="info",
                        max_length=30,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("action_url", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "appliance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="devices.appliance",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="devices.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_05b4bc_idx",
                    ),
                    models.Index(
                        fields=["is_read"], name="notificatio_is_read_9edb86_idx"
                    ),
                ],
            },
        ),
    ]
